### ISSUE TITLE
Memory Usage during Iventory Discovery 

### ISSUE THREAD

**Issue by ghost** [evoila/collectsphere#10]
I just ran collectsphere agains an environment with 14 ESXi hosts and 1990 VMs: I constantly run out of memory during the inventory discovery even with 8GB of RAM for the VM. I dont know what exactly uses so much space.

**Comment by dutchiechris** [comment]
Same issue.  I have 8 hosts and a few hundred VMs running and it needs GBs of memory!  Any ideas?

**Comment by ghost** [comment]
Hi dutchiechris, are you running from master of pyvmomi branch?

**Comment by dutchiechris** [comment]
Hi @mewald1, yes, 'git clone <repo>' and then copied files to module dirs from there and started it up.

**Comment by ghost** [comment]
@dutchiechris I think you misunderstood my question :) The git repository has 2 branches: "master" and "pyvmomi". Which are you using?

**Comment by dutchiechris** [comment]
@mewald1,

Sorry, I just cloned and did nothing else so it would be master.  Checking collectsphere.py it's using pysphere.

**Comment by ghost** [comment]
@dutchiechris, we started the project using pysphere but then @dennis1987  started rewriting it in pyvmomi if I remember correctly. Can you check to see if the pyvmomi version works better for you?

**Comment by dutchiechris** [comment]
Hi @mewald1 I flipped to the pyvmomi branch and it collects but doesn't have VM level stats, and the metrics naming is not very nice, so it's not a good fit for my purpose.
