### ISSUE TITLE
UnboundLocalError: local variable 'cluster_name' referenced before assignment

### ISSUE THREAD

**Issue by rhart211** [evoila/collectsphere#11]
I'm following the installation guide and when I run the test, it reports the following:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/root/collectsphere/collectsphere.py", line 669, in run
    len(inventory[cluster_name]['hosts'].keys()),
UnboundLocalError: local variable 'cluster_name' referenced before assignment

I'm running this on Ubuntu 14.04 with python 2.7.6.

**Comment by dennis1987** [comment]
Hi rhart211, it looks like you are using the master branch. Can you check if the pyvmomi version works better for you?

**Comment by rhart211** [comment]
Hi dennis1987,
That does seem to work. I had to add an indent at line 86, and comment "<<<<<< HEAD" at line 426. The test runs, but it only pulls 6 VM counters, and I have many more VMs than 6. Does the run.py only pull a few VMs?

**Comment by dennis1987** [comment]
Hi,

thanks for the advice! Today there was a wrong merge, but it is fixed now. 
By the way collectsphere only pulls data from machines which are powered on.
Let me know if it works now.

**Comment by rhart211** [comment]
Hey,
That did work, but it only pulls counters for 6 VMs, and not all 200 I have. All VMs are powered on. IS there something I need to do in VCenter to get the rest?

**Comment by dennis1987** [comment]
Hi,
that is weird. Which vCenter version are you using? It is tested witch v5.5. (maybe for v6 this could help [https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2107096](url) ). Has the account, which are you using, the privileges to change the statistic level? (this would be done in line 391). Maybe there is another privileges for collecting statistics report... (I ran this with administrator)

**Comment by rhart211** [comment]
Hey Dennis,
I tested with root and adminstrator. But when I run the test and it runs create_environment, it says that it's configured to grab 22 host counters and 6 vm counters. I'm running ESX 5.5.

**Comment by rhart211** [comment]
I noticed that the main script, collectsphere.py, does not disconnect from the VCenter Server. I think you should add that item.
