### ISSUE TITLE
No Module Named pyVM.connect

### ISSUE THREAD

**Issue by exbane** [evoila/collectsphere#12]
Good afternoon,

I'm attempting to set up collectsphere to collect against my vSphere 6 Update2 Infrastructure (using the VCSA Appliance).. All my hosts are also esxi 6 update2

My collector VM is ubuntu server 16.. I ran through the wiki documentation on here..

When I attempt to run the run-test.py script i get the following error.

root@feeder204:/etc/collectsphere# python run-test.py
Traceback (most recent call last):
  File "run-test.py", line 12, in <module>
    import collectsphere
  File "/etc/collectsphere/collectsphere.py", line 23, in <module>
    from pyVim.connect import SmartConnect, Disconnect
ImportError: No module named pyVim.connect
root@feeder204:/etc/collectsphere#

When i saw this error I did a pip install pyVim which installed additional packages but it still comes back with the same ImportError.. Thoughts?

**Comment by exbane** [comment]
nevermind - i had to run the following command to upgrade pyvmomi 

pip install --upgrade pyvmomi

Now when i run the script though i get the following error.. 
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by miquelMariano** [comment]
Same problem, but I have resolved it executing pip install --upgrade pyvmomi

**Comment by dennis1987** [comment]
Hi there,
I write down a setup routine in commit [1c7ef1d](https://github.com/evoila/collectsphere/commit/1c7ef1df5197984e75fe6a4b7fbe00713556c3bb). Now you can easily install collectsphere with 
`python setup.py install`
 I closed the SSL issue, see #16
