### ISSUE TITLE
Unhandled python exception in init callback: IndexError: list index out of range

### ISSUE THREAD

**Issue by Tiger736** [evoila/collectsphere#13]
Hi glad to be able to use your helper

I am currently experiencing a problem can help solve it?

Some error is displayed when you start

"Unhandled python exception in init callback: IndexError: list index out of range"

Thank you!!

**Comment by ipsecguy** [comment]
Same here, after fixing SmartConnect to not do Cert Checking.

BTW, I am on ESXI Free as this might be the cause (no performance manager in a non vSphere environment?)

python run-test.py

```
collectd [INFO]: configure_callback: Loaded config: name=test, host=192.168.0.179, port=80, verbose=True, username=root, password=******, host_metrics=3, vm_metrics=2, inventory_refresh_interval=600
Traceback (most recent call last):
  File "run-test.py", line 58, in <module>
    main()
  File "run-test.py", line 38, in main
    collectsphere.init_callback()
  File "/root/collectsphere/collectsphere.py", line 116, in init_callback
    env = create_environment(config)
  File "/root/collectsphere/collectsphere.py", line 395, in create_environment
    perfI = performanceManager.historicalInterval[0];
IndexError: list index out of range
```

**Comment by lkx007** [comment]
same problem @ipsecguy have you solved this problem??

**Comment by ipsecguy** [comment]
No, I guess my python and ESXi skills are limited...

**Comment by prjl** [comment]
Hey, I had the same error.
I tried to query the ESXi Host directly, but he needs a valid vSphere Center host.

**Comment by dennis1987** [comment]
Hi there,
sorry for my late response.
Do you have the "System.View" privilege for accessing the historicalInterval in the [PerformanceManger](http://pubs.vmware.com/vsphere-60/topic/com.vmware.wssdk.apiref.doc/vim.PerformanceManager.html#historicalInterval)? An administration user account should have the access.  May the "Modify historical intervals" privilege could help as well.
