### ISSUE TITLE
'Friendly Names' for Clusters, Hosts and VMs

### ISSUE THREAD

**Issue by ibishop100** [evoila/collectsphere#15]
Hi, great project, exactly what I was looking for, however when I run against my test VCenter, I get some internal name for the cluster, host and VM eg:

gauge-domain-c151.HostSystem.host-51.cpu.0.average.usage.perc
gauge-domain-c151.VirtualMachine.vm-216.cpu.all.average.usage.perc

Any way of getting the names that show up in the web client as tags?

**Comment by jblaine** [comment]
We have the same issue. I can't promise anything, but might magically somehow find a chance to look at the code for a solution...

**Comment by jblaine** [comment]
Assuming you're still using this, @ibishop100, do you also see all of your ESXi hosts having the same `*_all_average_usage_perc` values?

![all ESXi servers graphing same values](http://i.imgur.com/xsObK8j.png)

**Comment by dennis1987** [comment]
Hi there,
friendly names will be now supported with release v1.0.0. Please note that there has to import a typesDB for collectd.
Now, the missing entities will be displayed too (since v0.9.2).
