### ISSUE TITLE
Datacenter contains "ComputeResource" instead of "ClusterComputeResource"

### ISSUE THREAD

**Issue by varesa** [evoila/collectsphere#17]
In read_callback() the code looks for objects with _wsdlName of "ClusterComputeResource". However in my case it contains resources with the name "ComputeResource" instead.

My setup consists of three ESXi 6.5 nodes connected to a VCSA 6.5.

This is what I had to change to be able to discover hosts / VMs:

```
for datacenter in serviceInstance.RetrieveServiceContent().rootFolder.childEntity:
            collectd.info("DC name: " + datacenter._wsdlName)
            if datacenter._wsdlName == "Datacenter":
                for cluster in datacenter.hostFolder.childEntity:
                    collectd.info("Cluster name: " + cluster._wsdlName)
-                   if cluster._wsdlName == "ClusterComputeResource":
+                   if cluster._wsdlName == "ComputeResource":

```

**Comment by dennis1987** [comment]
Hi
thank you for the advice. You right, ClusterComputeResource is an extension of ComputeResource. I've pushed the patch in [694e6ae](https://github.com/evoila/collectsphere/commit/694e6ae996df918f4b802b453be3db7d50b9b1f2).
