### ISSUE TITLE
Metrics appear in graphite on disk, but can't graph

### ISSUE THREAD

**Issue by jblaine** [evoila/collectsphere#19]
I'm stumped. In case anyone has ideas... We've been using Graphite, collectd, and Grafana for years. I can't get Grafana (or the native Graphite web UI even) to display any of the data coming in from collectd for this plugin (and only this plugin).

whisper-dump.py shows there are values
```
#  /opt/graphite/bin/whisper-dump.py gauge-domain-c7_HostSystem_host-10_cpu_all_average_usage_perc.wsp
...
1: 1486421640,       1048
2: 1486421700,       1061
3: 1486421760,       1037
4: 1486421820,       1096
5: 1486421880,       1256
6: 1486421940,       1047
7: 1486422000,       2211
8: 1486422060,       2024
9: 1486422120,       1527
10: 1486422180,       1289
11: 1486422240,       1091
12: 1486422300,       1068
13: 1486422360,       1165
...
```

**Comment by jblaine** [comment]
Interesting. Seems the timestamps are all 5 hours in the future. No wonder I was seeing no data when viewing "Last 1 hour".

**Comment by jblaine** [comment]
Interesting. Seems the timestamps are all 5 hours in the future. No wonder I was seeing no data when viewing "Last 1 hour".

**Comment by dennis1987** [comment]
Hi there,
I've committed an bug fix for the timezone disaster. This means, from now the metrics will be collected based on the time of the vsphere host. At the parsing time, the timestamps will be converted to the local timezone of the collect host. Maybe this patches your issue.

**Comment by jblaine** [comment]
That fixed things. Thank you.
