### ISSUE TITLE
Bug - If Username has a "\" Character Login Attempt Fails

### ISSUE THREAD

**Issue by packtman** [evoila/collectsphere#26]
Hi, 

I would like to thank you for the awesome tool to pull vSphere data.

 **Bug:**
If the username has 

> \

 character in it, for example: 

> "**cool\awesome**".

 The tool would just accept 

> "coolawesome"

 and miss 

> \

 character, thus resulting into failed attempts.

Adding another 

> \

 solves the issue though. In our case `cool\\awesome`

 would work instead of "cool\awesome".

Let me know if you need more information.

Thanks.

**Comment by exbane** [comment]
Try using "cool\\awesome" Linux sees the \ as a termination

**Comment by dennis1987** [comment]
Hi there,

as a plugin of collectd, collectsphere uses the same syntax as collectd.conf.
To use "\" in your configuration file, you have to escape the char like @exbane commented before.
You can find more information in the man page of collectd or  [here](https://collectd.org/documentation/manpages/collectd.conf.5.shtml#description)

Best regards
