### ISSUE TITLE
Issue with collectsphere

### ISSUE THREAD

**Issue by ghost** [evoila/collectsphere#29]
Oct 18 11:16:27 prlesljmp001 collectd[8907]: configure_callback: Loaded config: name=######, host=######, port=443, verbose=True, username=######, password=******, host_metrics=3, vm_metrics=2, inventory_refresh_interval=600
Oct 18 11:16:28 prlesljmp001 collectd[8907]: create_environment: vCenter ###### does not contain any hosts. Cannot continue
Oct 18 11:16:28 prlesljmp001 collectd[8907]: Initialization complete, entering read-loop.
Oct 18 11:16:28 prlesljmp001 collectd[8907]: tcpconns plugin: Reading from netlink succeeded. Will use the netlink method from now on.
Oct 18 11:16:28 prlesljmp001 collectd[8907]: read_callback: entering environment: ######
Oct 18 11:16:28 prlesljmp001 collectd[8907]: Unhandled python exception in read callback: TypeError: 'NoneType' object has no attribute '__getitem__'

conf:
TypesDB "/usr/share/collectd/vmware-types.db"

<LoadPlugin "python">
    Globals true
</LoadPlugin>

<Plugin "python">
    Import "collectsphere"
    <Module "collectsphere">
        Name "######"
        Host "#######"
        Port "443"
        Verbose true
        VerifyCertificate false
        UseFriendlyName false
        Username "####"
        Password "####"
        Host_Counters "cpu.usage,mem.usage,disk.usage"
        VM_Counters "cpu.usage,mem.usage"
    </Module>
</Plugin>

**Comment by samceb** [comment]
Check the user has priviligies. Try first with an admin user.

**Comment by ghost** [comment]
I figured out.
Was trying with cluster but it wouldn't work.
It works with host direct.

Thanks for this nice work!

SP
