### ISSUE TITLE
VM Name Length Issue

### ISSUE THREAD

**Issue by ghost** [evoila/collectsphere#7]
In my lab 

```
collectd.collectsphere.collectsphere.gauge-lab_cluster.vm.vse-customer-router1_(5c4131)-0.cpu.all.usage.perc
```

was truncated to 

```
collectd.collectsphere.collectsphere.gauge-lab_cluster.vm.vse-customer-router1_(5c4131)-0.cpu.all.usage.pe
```

which means the string is still too long for collectd to handle. Since we have control of the string from element 4, the only idea I have to truncate the VM name even more.

**Comment by jhiemer** [comment]
Or switch to the new version of influxdb, where fields which describe the location of an entity are stored in tags:
http://influxdb.com/blog/2015/02/24/influxdb-v0_9_0-rc4_released_now_with_tags_and_more_unicorns.html

**Comment by ghost** [comment]
I don't see how influx can help. Collectsphere (1) dispatches values to Collectd (2) which in turn sends them to Graphite (3) which stores them in Whisper (4). From my understanding Influxdb can take the place of Whisper (4) but the issues we are seeing come from limitations in Collectd.

**Comment by jhiemer** [comment]
If I see the code here correctly, the usage of the collectd_plugin is able to send a custom entity (https://github.com/porjo/influxdb-collectd-proxy/blob/master/proxy.go#L247) instead of an endless long metric key. So skip graphite and whisper, directly write to influx.

**Comment by ghost** [comment]
For the moment I shortended vCD VM Names even further (commit 888349ed533c1f40911f4dc5df6058c1c82fe6db)
